### ISSUE TITLE
Not working Font Setting

### ISSUE THREAD

**Issue by k-kawaa** [Apartkktrain/SimpleIDE#1]
Not working Font Setting....

**Comment by k-kawaa** [comment]
別のフォームから指定されたフォームのコントロールを変更するにはどのようにすればよいでしょうか。

**Comment by automatic9045** [comment]
## 原因
CustomizeForm.csの24行目

```C#
MainForm cls = new MainForm();
```

新しいMainFormを作成してしまっており、表示されているMainFormを参照出来ていません。

## 解決法
CustomizeFormを作成するとき、表示されているMainFormの参照を渡すようにすると良いでしょう。

### CustomizeForm.cs
クラスの頭にMainFormの参照を格納するためのフィールドを追加します。

```C#
private MainForm mainForm;
```

コンストラクタでMainFormの参照を引数に取るようにします。

```C#
CustomizeForm(MainForm mainForm)
{
    InitializeComponent();
    this.mainForm = mainForm;
}
```

従来の24行目を削除し、25行目を以下のように書き換えます。

```C#
if (mainForm.ChangeFont(Font_dialog.Font))
```

### MainForm.cs
引数に `this` を指定するのがポイントです。  
この意味が分からない場合は調べてみて下さい。

```C#
private void オプションOToolStripMenuItem_Click(object sender, EventArgs e)
{
    CustomizeForm Form = new CustomizeForm(this);
    Form.Show();
}
```

## その他
C#には比較的厳密な命名規則があるので、把握しておいて下さい。[こちら](https://qiita.com/Ted-HM/items/67eddbe36b88bf2d441d)が参考になります。

**Comment by k-kawaa** [comment]
ありがとうございます。  
無事解決しました。
